config/routes.rb
Ministry::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :users

  resources :memberships

  resources :projects do
    collection do
      get 'search'
    end

    resources :milestones
    resources :obstacles
    resources :roles do
      collection do
        get 'names'
      end
    end

    member do
      get 'strategic'
      get 'tactical'

      post 'advance/:event' => 'projects#advance', as: 'advance'
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  include AASM, ProjectSearch

  # Sets up :tag_list, :tags
  acts_as_taggable

  after_touch {
    tire.update_index
  }

  include Tire::Model::Search
  include Tire::Model::Callbacks

  mapping do
    indexes :name, type: 'string', boost: 10, analyzer: 'snowball'
    indexes :roles do
      indexes :name, analyzer: 'snowball'
    end

    # tags and statuses are atoms, so there's no reason
    # to analyze them
    indexes :tags,           :index => :not_analyzed
    indexes :current_status, :index => :not_analyzed
  end

  def to_indexed_json
    # acts-as-taggable-on requires a reload for tags to be here
    self.reload
    ProjectSerializer.new(self).to_json
  end

  def self.facets
    return [ :tags, :current_status ]
  end

  # Relationships
  belongs_to :user, inverse_of: :projects
  belongs_to :status, inverse_of: :projects

  has_many :obstacles, inverse_of: :project, dependent: :destroy

  has_many :field_values, inverse_of: :project, dependent: :destroy
  has_many :fields, through: :field_values
  accepts_nested_attributes_for :field_values

  has_many :roles, inverse_of: :project, dependent: :destroy

  has_many :series_projects, inverse_of: :project, dependent: :destroy
  has_many :series, through: :series_projects

  has_many :milestones, inverse_of: :project, dependent: :destroy
  has_many :memberships, inverse_of: :project, dependent: :destroy
  has_many :users, through: :memberships

  # Validations
  validates :user,   presence: true
  validates :status, presence: true
  validates :name,   presence: true
  validates :public, inclusion: { in: [ true, false ] }

  # Callbacks
  after_create :setup_default_fields

  # State Machine for status transitions
  aasm_column :aasm_state

  aasm do
    state :pending, initial: true
    state :staffing
    state :scheduled
    state :working
    state :succeeded
    state :failed
    state :abandoned

    event :staff do
      transitions from: :pending, to: [ :staffing, :abandoned ]
    end

    event :schedule do
      transitions from: :staffing, to: [ :scheduled, :abandoned ], guard: :is_staffed?
    end

    event :work do
      transitions from: :scheduled, to: [ :working, :abandoned ]
    end

    event :succeed do
      transitions from: :working, to: :succeeded
    end

    event :fail do
      transitions from: :working, to: :failed
    end

    event :abandon do
      transitions from: [ :pending, :staffing, :scheduled, :working ], to: :abandoned
    end
  end

  def advance_to(state)
    may_name = "may_#{state}?".to_sym
    if self.respond_to?(may_name) and self.send(may_name)
      self.send(state.to_sym)
      self.save!
      true
    else
      logger.info "Unable to advance #{self.id} to #{state}, via #{may_name}"
      false
    end
  end

  # Object methods
  # Public: Returns a list of all managers on this project
  # Returns a collection of Users
  def managers
    User.where(id: user_id)
  end

  # Public: Return a list of Roles that are not fully staffed
  # Returns a result set of Roles
  def unfilled_roles
    role_to_quantity = {}
    self.roles.each do |role|
      role_to_quantity[role.id] = role.quantity
    end

    self.memberships.active.select("memberships.role_id, COUNT(*) as count").group("role_id").each do |record|
      if record.count >= role_to_quantity[record.role_id]
        role_to_quantity.delete(record.role_id)
      end
    end

    self.roles.where("id IN (:ids)", ids: role_to_quantity.keys)
  end

  # Public: Determines if the project is fully staffed
  # Returns boolean true if staffed entirely
  def is_staffed?
    self.unfilled_roles.count == 0
  end

  private
  def setup_default_fields
    return if self.field_values.size > 0

    Field.default_fields.each do |field|
      record = self.field_values.build(
        field_id: field.id,
        value: nil,
        user: self.user
      )
      # Value will be null, so we will skip validation on default.
      record.save!(validate: false)
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  load_and_authorize_resource
  #skip_authorize_resource only: [ :advance, :tactical, :strategic ]

  def index
    @project = current_user.projects.build
  end

  def search
    query   = params[:q]
    query   = '*' if query.blank?

    filters = params[:filter] ? filter_params : nil
    if query or filters
      @query   = query

      # If we have filters, create a lookup so
      # we can mark them as active in the view
      if filters
        @filters = {}
        filters.each do |facet, values|
          @filters[facet] = {}
          values.each do |term|
            @filters[facet][term] = true
          end
        end
      end

      @results = Project.search do
        query { string query }

        # Setup the faceting from the facetable fields (defaults)
        Project.facets.each do |facet|
          facet facet.to_s do
            terms facet
          end
        end

        # Filter if we have filters
        filter :terms, filters unless filters.nil?
      end
    end
  end

  def new
    @project = current_user.projects.build

    if flash[:project]
      @project.assign_attributes(flash[:project])
      @project.valid?
      flash.delete(:project)
    else
      # Nothing in Flash, we have to populate these manually.
      Field.default_fields.each do |field|
        @project.field_values.build(field: field, user: current_user)
      end
    end
  end

  def create
    data = project_params
    if data[:status_id].blank?
      # Need to populate with default status
      data[:status_id] = Status.initial_status.id
    end

    @project = current_user.projects.build(data)
    if @project.valid?
      @project.save!
      respond_to do |format|
        format.html { redirect_to project_path(@project), notice: t('created_project_notice') }
        format.json { render json: @project }
      end
    else
      flash[:project] = data
      respond_to do |format|
        format.html { redirect_to new_project_path, alert: t('created_project_alert') }
        format.json { render json: @project.errors }
      end
    end
  end

  def show
    @roles      = @project.roles
    @obstacles  = @project.obstacles
    @membership = current_user.memberships.includes(:role).where(project: @project)

    @view ||= 'strategic'

    render 'show'
  end

  def strategic
    @view = 'strategic'
    show
  end

  def tactical
    @view = 'tactical'
    show
  end

  def edit
    if flash[:project]
      @project.assign_attributes(flash[:project])
      @project.valid?
      flash.delete(:project)
    end

    @roles = @project.roles
  end

  def advance
    event = params[:event] || @project.aasm.current_state

    state_was = @project.aasm.current_state.capitalize

    if @project.advance_to(event)
      state = @project.aasm.current_state.capitalize
      respond_to do |format|
        format.html { redirect_to project_path(@project), notice: t('advanced_project_notice', state_was: state_was, state: state.to_s.capitalize) }
        format.json { render json: @project }
      end
    else
      respond_to do |format|
        format.html { redirect_to project_path(@project), alert: t('advanced_project_alert', state_was: state_was, event: event.to_s.capitalize) }
        format.json { render json: { error: t('advanced_project_alert', state_was: state_was, event: event.to_s ) } }
      end
    end
  end

  def update
    data = project_params
    #logger.ap data

    @project.assign_attributes(data)
    if @project.valid?
      @project.save!
      respond_to do |format|
        format.html { redirect_to project_path(@project), notice: t('updated_project_notice') }
        format.json { render json: @project }
      end
    else
      flash[:project] = data
      respond_to do |format|
        format.html { redirect_to edit_project_path(@project), alert: t('updated_project_alert') }
        format.json { render json: @project.errors }
      end
    end

  end

  def destroy

  end

  private
  def project_params
    params.require(:project).permit(:name, :tag_list, field_values_attributes: [ :id, :field_id, :value ])
  end

  def filter_params
    # Fetch the list of acceptable facetable terms from the Project model.
    list = Project.facets.map { |term| { term => [] } }
    params.require(:filter).permit(*list)
  end

  def load!
    @projects = current_user.projects.includes(:status, :roles, memberships: :user)

    id = params[:project_id] || params[:id]
    unless id.blank?
      @project = @projects.find(id.to_i)
    end
  end
end

app/views/projects/_breadcrumb.html.slim
ol.breadcrumb
  li
    = link_to @project.name, project_path(@project)
  li.active = terminator

app/views/projects/_form.html.slim
= simple_form_for @project do |f|
  = f.input :name
  = f.input :description
  = f.input :public, boolean_style: :inline
  = f.input :tag_list, label: t('project_tag_list_label'), input_html: { data: { role: "tagsinput" } }, hint: t('project_tag_input_hint')

  = f.simple_fields_for :field_values do |fv|
    - if not @project.new_record? or ( @project.new_record? and not fv.object.field.retrospective )
      = fv.input :field_id, as: :hidden
      = fv.input :value, label: fv.object.field.name, required: fv.object.field.required

  div.form-actions.row
    div.col-xs-4
      = f.submit t('save_button_html'), class: 'btn btn-primary'
    div.col-xs-4.offset-xs-4
      = link_to t('cancel_button_html'), projects_path, class: 'btn btn-default'

- unless @project.new_record?
  h3 Project Roles

  = render "roles/display", editable: true

app/views/projects/_list.html.slim
table.table.table-striped
  tbody
    - @projects.each do |project|
      tr
        td = link_to project.name, project_path(project)
        td &nbsp;
  tfoot
    tr
      td colspan="2"
        = link_to t('add_project_button_html'), new_project_path, class: 'btn btn-default'

app/views/projects/_search_results.html.slim
div.container
  div.col-xs-2
    - @results.facets.each do |facet, values|
      h4 = facet.humanize
      ul.nav.nav-pills.nav-stacked
        - values['terms'].each do |f|
          li class=(@filters.has_key?(facet) and @filters[facet][f['term']] ? 'active' : '')
            a href=search_projects_path(q: @query, filter: { facet => [ f['term'] ] })
              = f['term']
              span.badge.pull-right = f['count']
  div.col-xs-10
    - @results.each do |result|
      div.project
        h1 = link_to result[:name], project_path(result[:id])

    small = t('search_result_statistics', count: @results.size)

app/views/projects/_strategic.html.slim
- if @obstacles.size > 0
  = render "obstacles/display"
- else 
  div.btn-group
    = link_to t('add_obstacle_button.html'), new_project_obstacle_path(@project), class: 'btn btn-default'
  p
    | TODO: Add obstacles help text

app/views/projects/_tactical.html.slim
- if @project.roles.size > 0
  = render "roles/display"
- else
  p
    | TODO: Add role help text

app/views/projects/edit.html.slim
= render "form"

app/views/projects/index.html.slim
h1 = t('projects_title.html')

- if @projects.size == 0
  div.jumbotron
    h1 You have no projects!

    = simple_form_for @project do |f|
      = f.input :name, label: 'Start a new project'
      = f.submit t('save_button_html'), class: 'btn btn-primary btn-large'

- else
  = render "list"

app/views/projects/new.html.slim
= render "form"

app/views/projects/search.html.slim
h1 Project Search

form.horizontal-form role="role" method="get" action=search_projects_path
  div.row
    div.form-group.col-xs-10
      input.form-control.col-xs-10 type="text" placeholder="Search" name="q" 
    button.btn.btn-primary type="submit"
      | Go

- if @results
  = render "search_results"

app/views/projects/show.html.slim
h1 = @project.name

- if can? :manage, @project
  div.btn-toolbar
    = link_to t('edit_button_html'), edit_project_path(@project), class: 'btn btn-default'
    div.btn-group.pull-right
      span.btn.btn-info.btn-disabled = @project.aasm.current_state.capitalize
      - @project.aasm.events.each do |event|
        = link_to t('advance_state_button_html', event: event.to_s.capitalize), advance_project_path(@project, event), method: :post, class: 'btn btn-default'

- else
  p = t('current_state_label_html', state: @project.aasm.current_state.capitalize)

- @project.field_values.populated.each do |fv|
  div.field
    h3 = fv.field.name 
    p = simple_format fv.value

- @membership.each do |membership|
  - if membership.needs_approval?
    = render "roles/pending_approval", membership: membership
  - elsif membership.needs_acceptance?
    = render "roles/pending_acceptance", membership: membership
  - else
    = render "roles/user_status", membership: membership

ul.nav.nav-tabs
  li class=(@view=="strategic" ? "active" : "")
    = link_to t('strategic_view_link_html'), strategic_project_path(@project)
  li class=(@view=="tactical" ? "active" : "")
    = link_to t('tactical_view_link_html'), tactical_project_path(@project)

div.container
  = render @view