config/routes.rb
Ministry::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :users

  resources :memberships

  resources :projects do
    collection do
      get 'search'
    end

    resources :milestones
    resources :obstacles
    resources :roles do
      collection do
        get 'names'
      end
    end

    member do
      get 'strategic'
      get 'tactical'

      post 'advance/:event' => 'projects#advance', as: 'advance'
    end
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :project, inverse_of: :roles, touch: true

  has_many :memberships, inverse_of: :role
  has_many :users, through: :memberships

  validates :project, presence: true

  validates :name, presence: true
  validates :quantity, numericality: { only_integer: true, greater_than: 0 }

  def self.default_role_names
    [ 'Product Manager', 'Developer', 'Documenter', 'Tester', 'Evangelist' ]
  end

  def pending_for(user)
    memberships.where(user: user, approved: false, accepted: false, active: true)
  end

  # Determine if a user can apply, based on if they have a pending membership
  # or if the project is public.
  def can_apply?(user)
    return true
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_user!

  load_and_authorize_resource :project
  load_and_authorize_resource :role, through: :project

  def index
  end

  def names
    list = @project.roles.pluck(:name) + Role.default_role_names
    list.uniq!
    list.compact!

    respond_to do |format|
      format.json { render json: list, root: false }
    end
  end

  def new
    @role = @project.roles.build

    if flash[:role]
      @role.assign_attributes(flash[:role])
      @role.valid?
      flash.delete(:role)
    end
  end

  def create
    data = role_params
    @role = @project.roles.build(data)
    if @role.valid?
      @role.save!
      respond_to do |format|
        format.html { redirect_to project_path(@project), notice: t('created_role_notice') }
        format.json { render json: @role }
      end
    else
      flash[:role] = data
      respond_to do |format|
        format.html { redirect_to new_project_role_path(@project), alert: t('created_role_alert') }
        format.json { render json: @role.errors }
      end
    end
  end

  def show
    if can? :manage, @role
      render :edit and return
    end

    @pending = @role.pending_for(current_user).first
    if @pending.nil?
      @can_apply = @role.can_apply?(current_user)
    end
  end

  def edit
    if flash[:role]
      @role.assign_attributes(flash[:role])
      @role.valid?
      flash.delete(:role)
    end
  end

  def update
    data = role_params

    @role.assign_attributes(data)
    if @role.valid?
      @role.save!
      respond_to do |format|
        format.html { redirect_to project_path(@project), notice: t('updated_role_notice') }
        format.json { render json: @role }
      end
    else
      flash[:role] = data
      respond_to do |format|
        format.html { redirect_to edit_project_role_path(@project, @role), alert: t('updated_role_alert') }
        format.json { render json: @role.errors }
      end
    end

  end

  def destroy
    @role.destroy

    respond_to do |format|
      format.html { redirect_to project_path(@project), notice: t('removed_role_notice') }
      format.json { render json: @project }
    end
  end

  private
  def role_params
    params.require(:role).permit(:name, :description, :admin, :quantity)
  end

  def load!
    @project = current_user.projects.includes(:status, :roles, memberships: :user).find(params[:project_id].to_i)
    @roles   = @project.roles

    if params[:id]
      @role = @project.roles.find(params[:id].to_i)
    end
  end
end

app/views/roles/_apply_form.html.slim
= simple_form_for @role.memberships.build(project: @project, role: @role) do |f|
  = f.hidden_field :project_id
  = f.hidden_field :role_id

  = f.input :note

  div.form-actions
    = f.submit t('apply_button_html'), class: "btn btn-primary"

app/views/roles/_breadcrumb.html.slim
ol.breadcrumb
  li
    = link_to @project.name, project_path(@project)
  - if @role.nil?
    li.active = terminator
  - else
    li = link_to t('roles_label'), project_roles_path(@project)
    li.active = terminator

app/views/roles/_display.html.slim
div id="role-editor" data-add-role-uri=project_roles_path(@project) data-role-uri=project_role_path(@project, '{id}')
  table.table.table-striped
    thead
      th Role
      td Needed
      td Filled
      td
        | &nbsp;
    tbody data-bind="foreach: roles"
      tr
        td data-bind="text: name"
        td data-bind="text: quantity"
        td data-bind="text: filled_count"
        td = link_to t('view_role_button_html'), '#', data: { bind: 'css: { disabled: !id() }, attr: { href: roleURL() }' }, class: 'btn btn-default btn-mini'
    - if local_assigns[:editable] == true 
      tfoot.add-role id="add-role-#{@project.id}"
        tr data-bind="enterkey: addRole"
          td
            div.form-group data-bind="css: { 'has-success': newRoleName.isModified() && newRoleName.isValid(), 'has-error': newRoleName.isModified() && !newRoleName.isValid() }"
              input.form-control name="role" data-bind="typeahead: newRoleName, value: newRoleName" id="newRoleName" data-prefetch=names_project_roles_path(@project)
          td colspan="2"
            div.form-group data-bind="css: { 'has-success': newRoleQuantity.isModified() && newRoleQuantity.isValid(), 'has-error': newRoleQuantity.isModified() && !newRoleQuantity.isValid() }"
              label
                input.form-control name="quantity" data-bind="value: newRoleQuantity" type="number" min="1"
          td
            a.btn.btn-default data-bind="click: addRole, css: { 'btn-danger': (newRoleName.isModified() && !newRoleName.isValid()) || !newRoleQuantity.isValid() }" href="#"
              = t('add_role_button_html')

javascript:
  var roles = #{raw @roles.to_json};

app/views/roles/_form.html.slim
= simple_form_for [ @project, @role ] do |f|
  div.row
    div.col-xs-2
      p
        | This project needs
    div.col-xs-2
      = f.input :quantity, class: 'col-xs-2', label: false
    div.col-xs-8
      = f.input :name, label: false, input_html: { data: { role: 'typeahead', prefetch: names_project_roles_path(@project) } }

  = f.input :description, label: false, placeholder: 'What does this person need to do to succeed?'

  div.form-actions.row
    div.col-xs-4
      = f.submit t('save_button_html'), class: 'btn btn-primary'
    div.col-xs-4.offset-xs-4
      = link_to t('cancel_button_html'), project_path(@project), class: 'btn btn-default'

app/views/roles/_inline_form.html.slim
= simple_form_for [ @project, role ], remote: true do |role_fields|
  div.row
    div.col-xs-6
      = role_fields.input :name, input_html: { data: { role: "typeahead", source: names_project_roles_path(@project) } }, label: labels ? t('role_name_label') : false
    div.col-xs-3
      = role_fields.input :quantity, label: labels ? t('role_quantity_label') : false
    div.col-xs-3
      / TODO: Need a top margin on this button
      = role_fields.submit t('add_role_button_html'), class: 'btn btn-default'

app/views/roles/_inline_view.html.slim
div.row id="role-#{role.id}"
  div.col-xs-6
    h3 = role.name
  div.col-xs-3
    h3 
      | #{role.filled_count} / #{role.quantity}
  div.col-xs-3
    = link_to t('edit_button_html'), project_role_path(@project, role), class: 'btn btn-default'

app/views/roles/_invite_form.html.slim
h3 = t('invite_user_title.html')
p = t('invite_user_help.html')

= simple_form_for @role.memberships.build(project: @project) do |f|
  = f.hidden_field :project_id
  = f.hidden_field :role_id

  = f.input :email
  div.form-actions
    = f.submit t('invite_button_html'), class: 'btn btn-primary'

app/views/roles/_pending_approval.html.slim
div.alert.alert-info
  h4 = t('role_needs_approval_title_html', role: membership.role.name, membership_path: membership_path(membership))
  p = t('role_needs_approval_text')

app/views/roles/_user_status.html.slim
div.alert.alert-success
  h4 = t('user_status_in_project', role: membership.role.name)
  - unless membership.note.blank?
    p = simple_format membership.note
  div.btn-group
    = link_to t('edit_button_html'), membership_path(membership), class: 'btn btn-default'

app/views/roles/create.js.erb
var node      = $("<%= escape_javascript(render ((@role.new_record? or not @role.valid?) ? 'roles/inline_form' : 'roles/inline_view'), role: @role, labels: @project.roles.count == 0) %>"),
    container = $("#role-list");

<% if @role.new_record? %>
  container.find("input[data-role='typeahead']").typeahead("destroy");
  container.find('form#new_role').replaceWith(node);
  container.find("input[data-role='typeahead']").each(function() {
    $(this).typeahead({
      prefetch: $(this).data('source')
    });
  });
  container.append(node);
<% else %>
  node.insertBefore(container.find('hr'))
  container.find('form#new_role').reset();
<% end %>

app/views/roles/edit.html.slim
div.page-header
  h1 = @role.name

  div.row
    div.col-xs-11
      = render "projects/breadcrumb", terminator: t('edit_role_breadcrumb', role: @role.name)
    div.col-xs-1
      = link_to t('delete_role_button_html'), project_role_path(@project, @role), method: :delete, data: { confirm: t('delete_role_confirmation') }, class: 'btn btn-danger pull-right'

= render "form"

- if can?(:manage, @role) and @role.filled_count < @role.quantity
  hr
  = render "invite_form"

app/views/roles/index.html.slim
div.page-header
  h1 = t('project_roles_title.html', project: @project.name)

  div.row
    div.col-xs-10
      = render "breadcrumb", terminator: t('roles_label')

h1 = @roles.size

= render "roles/display", editable: can?(:manage, @project)

app/views/roles/new.html.slim
Apply!

app/views/roles/show.html.slim
div.page-header
  h1 = @role.name

  div.row
    div.col-xs-10
      = render "breadcrumb", terminator: t('edit_role_breadcrumb', role: @role.name)

- if @pending
  = render "pending_role"
- elsif @can_apply
  h3 = t('apply_role_header')
  = render "apply_form"
- else 
  p Cannot apply for this role