config/routes.rb
Ministry::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  root 'welcome#index'

  resources :users

  resources :memberships

  resources :projects do
    collection do
      get 'search'
    end

    resources :milestones
    resources :obstacles
    resources :roles do
      collection do
        get 'names'
      end
    end

    member do
      get 'strategic'
      get 'tactical'

      post 'advance/:event' => 'projects#advance', as: 'advance'
    end
  end

end

app/views/layouts/application.html.erb
<%
  show_sidebar   = content_for?(:sidebar)
  layout_classes = show_sidebar ? 'col-xs-12 col-sm-9' : 'col-xs-12'
%>
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../docs-assets/ico/favicon.png">

    <title>Ministry</title>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>">The Ministry of Potential Projects</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <% if signed_in? %>
              <li><%= link_to 'My Projects', projects_path %></li>
            <% else %>
              <li class="active"><a href="<%= root_path %>">Home</a></li>
            <% end %>
            <% if @project and not @project.new_record? %>
              <li><%= link_to 'Overview', project_path(@project) %></li>
            <% end %>
          </ul>
          <% if signed_in? %>
            <form class="navbar-form navbar-right" action="<%= search_projects_path %>">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Find Projects" name="q">
              </div>
              <button type="submit" class="btn btn-default">Go</button>
            </form>
          <% end %>
        </div><!-- /.nav-collapse -->
      </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="primary container">

      <div class="row">

        <div class="<%= layout_classes %>">
          <%= render "shared/messages" %>

          <%= yield %>
        </div><!--/span-->
        <% if show_sidebar %>
          <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar" role="navigation">
            <%= yield :sidebar %>
          </div><!--/span-->
        <% end %>
      </div><!--/row-->

    </div><!--/.container-->
    <div id="footer">
      <div class="container">
        <div class="social">
          <ul class="social-buttons">
            <li>
              <iframe class="github-btn" src="http://ghbtns.com/github-btn.html?user=jshirley&amp;repo=ministry&amp;type=watch&amp;count=true" width="100" height="20" title="Star on GitHub"></iframe>
            </li>
            <li>
              <iframe class="github-btn" src="http://ghbtns.com/github-btn.html?user=jshirley&amp;repo=ministry&amp;type=fork&amp;count=true" width="102" height="20" title="Fork on GitHub"></iframe>
            </li>
          </ul>
        </div>
        <ul class="footer-links">
          <p><a href="https://github.com/jshirley/ministry">The Ministry of Potential Projects</a>.</p>
        </ul>
      </div>
    </div>
  </body>
</html>